### ISSUE TITLE
Command line interface?

### ISSUE THREAD

**Issue by tseemann** [gtonkinhill/fastbaps#11]
Would it be possible to add a command line interface version of this tool?

**Comment by gtonkinhill** [comment]
I think this should be possible using Rscript. Would this suffice? It would still require installing fastbaps using R/conda.

**Comment by gtonkinhill** [comment]
I have added a command line script in 37435c2031524dd49dbbc8734eb193d485d3778b. It's located in the `fastbaps/inst` subdirectory. I will look at updating the conda recipe to put this in the users path. If I get a chance I'll see if I can get it setup in a docker instance as well.

**Comment by gtonkinhill** [comment]
This is now included in the bioconda recipe.

**Comment by tseemann** [comment]
@gtonkinhill thanks so much!

**Comment by johnlees** [comment]
I think `optparse` might need to be added to the dependency lists for this

**Comment by johnlees** [comment]
Also v. minor issue if reopening this, phylogeny is misspelled as 'phylogney' in the options

**Comment by gtonkinhill** [comment]
I'd forgotten about this but it should be fixed in the latest release.
