### ISSUE TITLE
Information on Symmetric Prior

### ISSUE THREAD

**Issue by noahaus** [gtonkinhill/fastbaps#16]
Greetings,

I had a question about what the optimized symmetric prior is in relation to in the population clustering. I imagine that when it says that it is symmetric,  this is based on the assumption that all groups will be engaging in gene flow 'symmetrically' but I also have no idea what it could mean! Can you please help understand what this prior is actually assuming in the bayesian HC?

**Comment by gtonkinhill** [comment]
Hi,

Not quite. 'Symmetric' refers to the parameters of the prior Dirichlet distribution for the allele frequencies. In this case it specifies that they are all the same. This uniform prior on the allele frequencies is the same as that used in the [Structure](https://www.genetics.org/content/155/2/945) publication.
