### ISSUE TITLE
Different results with "optimise.symmetric" and "optimised.symmetric"

### ISSUE THREAD

**Issue by valery-shap** [gtonkinhill/fastbaps#17]
Hello,

Thank you for the great tool.
When I use:
`sparse.data <- optimise_prior(sparse.data, type = "optimise.symmetric")`
I have 4 clusters.
when:
`sparse.data <- optimise_prior(sparse.data, type = "optimised.symmetric")`
I have 3 clusters.
with the same data.

What could be the reason? 

A lot of thanks,
Valery

**Comment by gtonkinhill** [comment]
Hi,

Sorry for the slow reply. I have been away on break. Would it be possible to send a reproducible example?
It might be necessary to set the random seed to ensure I can reproduce the behaviour you are seeing using `set.seed(123)`

**Comment by valery-shap** [comment]
Hello,

thank you for reply! Yes, of course, I could send, is this mail gt4@sanger.ac.uk ok?
I've done set.seed(123) and have the same results 3 clusters with optimisED and 4 clusters with optimisE option.

Valery

**Comment by gtonkinhill** [comment]
Hi,

Thanks for your email. I am not sure what is going wrong as the tool should throw an error if you try to used 'optimisED.symmetric' as it is an invalid option. When I attempt to reproduce the issue I get

```
sparse.data <- optimise_prior(sparse.data, type = "optimised.symmetric")
Error in optimise_prior(sparse.data, type = "optimised.symmetric") : 
  Invalid value for type. Must be one of 'optimise.symmetric','symmetric', 'hc', 'optimise.baps' or 'baps'
```

In regard to your second question about whether the clusters should always correspond to clades in the tree, this is not the case as the `fastbaps` algorithm makes different assumptions to phylogeny reconstruction methods. However, if you are confident in your phylogeny it is possible to restrict `fastbaps` to only consider clusters that match with the tree. This is outlined in more detail in the documentation but can be run as

```
# The file names given here should be replaced with your files.
sparse.data <- import_fasta_sparse_nt(fasta.file.name, prior = "baps")
iqtree <- phytools::read.newick(newick.file.name)

iqtree.rooted <- phytools::midpoint.root(iqtree)
best.partition <- best_baps_partition(sparse.data, iqtree.rooted)
```
