### ISSUE TITLE
Hashes in filenames cause name match issues

### ISSUE THREAD

**Issue by johnlees** [gtonkinhill/fastbaps#18]
Using the 'sanger' name format of run_lane#tag in input alignments or trees get converted to run_lane_tag, which then causes sample name mismatches if used in a pipeline. Would it be possible to escape the hashes and include them in the output?

I am running a command of the form:
```
run_fastbaps -p 'baps' -i input.aln -o fastbaps_clusters.txt -l 2 --phylogeny=input.tree -t 8
```

**Comment by gtonkinhill** [comment]
Hi John,

I'm having trouble reproducing the behaviour. When I run the script locally it seems to keep the '#'. I've attached the example inputs I am using. Do these work on your system?

```
Rscript run_fastbaps -i test.fasta -o test_fastbaps.txt -l 2 --phylogeny=test.tree -t 2
```

Gives

```
head test_fastbaps.txt
Isolates,Level 1,Level 2
1#1,9,23
2#2,9,23
3#3,9,23
4#4,3,6
5#5,9,27
6#6,9,27
7#7,9,27
8#8,3,5
9#9,2,4
```


[test_data.zip](https://github.com/gtonkinhill/fastbaps/files/9168695/test_data.zip)

**Comment by johnlees** [comment]
Hi Gerry,
Ah really sorry, I think I may have got it wrong where in our pipeline this was happening. I actually think it was the iq-tree output being renamed in this way, which meant the names between the alignment and tree no longer matched (but this gave an error in fastbaps, despite it being an input issue). Sorry for wasting time!!
