### ISSUE TITLE
how to force fastbaps to be consistent by using the best_baps_partition function with multi_res_baps

### ISSUE THREAD

**Issue by shaodongyan** [gtonkinhill/fastbaps#23]

**Comment by gtonkinhill** [comment]
Hi,

I am afraid this is not currently implemented but can be done manually. I will look at adding this functionality soon.

**Comment by gtonkinhill** [comment]
Hi,

Someone has just reminded me that I have already implemented this in the `multi_level_best_baps_partition` function.
Please give this a try and let me know if you run into any issues.
