### ISSUE TITLE
can fastbaps run in parallel?

### ISSUE THREAD

**Issue by zzsunday** [gtonkinhill/fastbaps#24]
hi, the software fastbaps is really fantastic.

but, I have a question. Can fastbaps run in multiple cpus. Recently, I have a fa file , the size of file was 900M, when I run optimise_prior step, it is so slow. so I ask whether the fastbaps can run in multiple cpus.

**Comment by gtonkinhill** [comment]
Hi,

The main function in fastbaps makes use of multiple cpu's but only if the package is compiled with `openmp`. 

Unfortunately, the `optimise_prior` function is only single-threaded at the moment. You may be able to speed things up a bit by first reducing your alignment to only variable sites using [snp-sites](https://github.com/sanger-pathogens/snp-sites)
