### ISSUE TITLE
Level 1 and 2 cluster

### ISSUE THREAD

**Issue by tthye1** [gtonkinhill/fastbaps#25]
Hi Gerry,

I work on a project with about 200 Campylobacter isolates. I have created SNP based and cgMLST based distance matrices and phylogenies and clustered the isolates with fastbaps and hierCC.
My question is how the fastbaps level 1 and 2 compare to the levels of the multi-clustering scheme of hierCC software used by Enterobase. Are they comparable, and which software works best for which data set (SNPs or cgMLST alleles)?

Best,

Thorsten

**Comment by gtonkinhill** [comment]
Hi Thorsten,

I'm afraid I don't have a lot of experience with hierCC so I'm not sure exactly how it compares. I mostly use SNP data when running fastbaps although it should work with cgMLST as well.

In terms of running fastbaps, it's often worth considering the choice of prior used in the algorithm. This can go from conservative (less clusters) using the 'symmetric' prior up to more sensitive (more clusters) using the 'optimised.baps' prior which is tailored to each dataset. If you have a phylogeny you are confident in you could also consider conditioning on the tree which will ensure that all clusters are consistent with the phylogeny.

**Comment by tthye1** [comment]
Hi Gerry,

Thanks for your input. I will run both softwares on my datasets and compare the results.

Best,

Thorsten
