### ISSUE TITLE
Alignment tool

### ISSUE THREAD

**Issue by jsgounot** [gtonkinhill/fastbaps#26]
Hi,

this issue is more related to your paper. I was curious how you aligned the sequences/genomes from your bacterial dataset. Do you have a recommended way to produce an alignment from a set of bacterial genomes before sending it fastbaps?

Thanks,
JS

**Comment by gtonkinhill** [comment]
Hi,

I generally use [Snippy](https://github.com/tseemann/snippy). You could also take a look at [SKA](https://github.com/bacpop/ska.rust) which uses a reference free based approach.

**Comment by jsgounot** [comment]
Hi,

I thought you were working with assemblies and not reads, my bad. Thanks for your recommendations.

JS
