### ISSUE TITLE
Instalation failling on Windows

### ISSUE THREAD

**Issue by HeloisaAllgayer** [gtonkinhill/fastbaps#6]
I have this issue:

collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'fastbaps'
* removing 'C:/Users/user/Desktop/SPARTA_Windows-master/R_local/library_local/fastbaps'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/user/AppData/Local/Temp/Rtmps5b0zz/file1ef43330616e/fastbaps_1.0.0.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by gtonkinhill** [comment]
Hi, sorry for the delay in getting back to you. I'm working to fix the windows installation at the moment and will hopefully have it up and working soon. I'm having to use a virtual machine as I don't own a windows laptop which makes things a bit slower.

**Comment by HeloisaAllgayer** [comment]
Hi, how are you?
If you need I can test it as you go about fixing it.


Thanks


Em qui, 4 de abr de 2019 6:35 AM, Gerry Tonkin-Hill <
notifications@github.com> escreveu:

**Comment by gtonkinhill** [comment]
Hi,

It should hopefully be working now. Please give it a go and let me know if you run into any issues. Thanks for pointing out the problem.
