### ISSUE TITLE
Issue loading data

### ISSUE THREAD

**Issue by slvrshot** [gtonkinhill/fastbaps#7]
I ran this, ensuring I am in the correct working directory with my multi-fasta alignment file: 

```
fasta.file.name <- system.file("exdata","test.fasta", package = "fastbaps")
sparse.data <- import_fasta_sparse_nt(fasta.file.name)
```

and it returns:

`Error in import_fasta_sparse_nt(fasta.file.name) : Can't locate file `

Please help.

**Comment by johnlees** [comment]
Try:
```
sparse.data <- import_fasta_sparse_nt("test.fasta")
```

(The example is for loading data that comes with the package)

@gtonkinhill - it might be an idea to add this to the README, as I also ran into this error the first time I came across `system.file`

**Comment by slvrshot** [comment]
> Try:
> 
> ```
> sparse.data <- import_fasta_sparse_nt("test.fasta")
> ```
> 
> (The example is for loading data that comes with the package)
> 
> @gtonkinhill - it might be an idea to add this to the README, as I also ran into this error the first time I came across `system.file`

Yeah the tutorial was a little confusing for importing my own files. I figured it was loading the tutorial data using `system.file`. 

Thanks a bunch.

**Comment by slvrshot** [comment]
@johnlees 

One last question is there a way to export the BAP clusters to text file if you already have a tree generated using an software such as RaxML?

**Comment by sdwfrost** [comment]
You may get some additional guidance from looking at the analyses in the repository associated with the manuscript: [https://github.com/gtonkinhill/fastbaps_manuscript](https://github.com/gtonkinhill/fastbaps_manuscript)
